---
title: "このサイトについて"
description: |
  このウェブサイト・運営する私自身について
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 私について

- 氏名: 瓜生真也 (Shinya Uryu)
- 所属: 国立環境研究所 (National Institute for Environmental Studies)

Hi! I'm Shinya Uryu, a engineer working with [National Institute for Environmental Studies (NIES)](https://www.nies.go.jp), and member of HOXO-M that Japanese young data scientist group. Passionate about data science, management and statistics. My favorite open-source language is [R](https://www.r-project.org/). I'm a [RStudio](https://www.rstudio.com/) fanboy. I got my MS in Plant Ecology, Yokohama National University. I love to plants, especially oak (*Quercus*) trees. I currently live in Tsukuba, Japan.

### 興味関心

- `r set.seed(123); emo::ji("graph")` Data Visualisation
- Geo-spatial
- Statistics
- Reproducible Research

### SNS

- `r icon::fa("twitter")` Twitter: [\@u_ribo](http://twitter.com/u_ribo)
- `r icon::fa("github")` GitHub: [uribo](http://github.com/uribo)

## スポンサー

下記の方々よりOSS活動に対する支援をいただいております（2020年10月2日現在 アカウントのアルファベット順）。ありがとうございます。

[ak9782427](https://github.com/ak9782427]), [ito4303](https://github.com/ito4303), [kanji14134](https://github.com/kanji14134), [katsurakob](https://github.com/katsurakob), [niszet](https://github.com/niszet), [siero5335](https://github.com/siero5335), [takehikoihayashi](https://github.com/takehikoihayashi), [ytknzw](https://github.com/ytknzw), [yutannihilation](https://github.com/yutannihilation)

スポンサーを検討される方は詳細ページ https://github.com/sponsors/uribo をご覧ください。
