---
title: "プレゼンテーションのスライド資料"
description: |
  プレゼンテーションのスライド資料をまとめています。
output:
  distill::distill_article:
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 次の発表

現在発表予定の講演はありません。決定次第、このページにてお知らせします。

## 過去

http://speakerdeck.com/s_uryu

### 今こそ、data.tableパッケージを学ぼう！

<script async class="speakerdeck-embed" data-id="e0e3f538dbe5417c8f0f23800685b25d" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>

- `r icon::fa("calendar")` Date: 2020-08-01
- `r icon::fa("link")` Link: https://speakerdeck.com/s_uryu/datatable1130
- `r icon::fa("angle-right")` Description:  Tokyo.R#87 http://tokyor.connpass.com/event/182672/ での発表スライド
- `r icon::fa("github")` Code: -

### R 10年の歩み、そしてこれから

<script async class="speakerdeck-embed" data-id="6792f66f19344f3795eaf748aca3d4b7" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>

- `r icon::fa("calendar")` Date: 2020-01-25
- `r icon::fa("link")` Link: https://speakerdeck.com/s_uryu/tokyor10years
- `r icon::fa("angle-right")` Description: Tokyo.R#83 Tokyo.R10周年記念回
- `r icon::fa("github")` Code: -

### 2019年版Rパッケージ開発の手引き

<script async class="speakerdeck-embed" data-id="c3c7055ad8d144208978ceac950fed93" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>

- `r icon::fa("calendar")` Date: 2019-11-16
- `r icon::fa("link")` Link: https://speakerdeck.com/s_uryu/pkg-dev
- `r icon::fa("angle-right")` Description: Spa Tech#02
- `r icon::fa("github")` Code: -

### データ分析者のためのRStudio活用術

- `r icon::fa("calendar")` Date: 2019-10-26
- `r icon::fa("link")` Link: https://speakerdeck.com/s_uryu/pyrintegration
- `r icon::fa("angle-right")` Description: Tokyo.R #82
- `r icon::fa("github")` Code: -

### tidymodelsによるモデル構築と運用

- `r icon::fa("calendar")` Date: 2019-08-31
- `r icon::fa("link")` Link: https://speakerdeck.com/s_uryu/tidymodels
- `r icon::fa("angle-right")` Description: Fukuoka.R#15
- `r icon::fa("github")` Code: http://github.com/uribo/190831_fukuokar15

### データ分析における特徴量エンジニアリング

- `r icon::fa("calendar")` Date: 2019-07-10
- `r icon::fa("link")` Link: https://speakerdeck.com/s_uryu/feature-engineering-recipes
- `r icon::fa("angle-right")` Description: Spa Tech#02
- `r icon::fa("github")` Code: https://github.com/uribo/190710-johokiko
