on:
  push:
    branches:
      - master
    paths:
      - '**.Rmd'

name: distill

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TZ: Asia/Tokyo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@master
        
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/Library/Application Support/renv
          key: ${{ runner.os }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore(confirm = FALSE)'
          R -e 'renv::install(c("purrr", "fs", "rmarkdown"))'

      - name: Build pages
        run: Rscript -e 'purrr::walk(fs::dir_ls("_posts", recurse = TRUE, regexp = ".Rmd$"), rmarkdown::render)'

      - name: Build site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir _site
